version: '3.1'
services:
    nginx:
        image: nginx
        container_name: nginx_proxy
        volumes:
            - ./cert.pem:/etc/nginx/ssl/fullchain.pem
            - ./key.pem:/etc/nginx/ssl/privkey.pem
            - ./config/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            - 443:443
    python_app:
        build:
            context: ./
            dockerfile: PythonDockerfile
        image: python:3.12
        container_name: python_app
        env_file:
            - .env
            - .env.example

        # порт запуска приложения захардкожен тут и в ngiinx.conf
        # менять нет смысла, если хочется достучаться снаружи, просто выставляем нужный порт в директиву porst
        command:  ["uvicorn", "lti_auth.app:app", "--host", "0.0.0.0", "--port", "8001", "--ssl-keyfile", "../key.pem", "--ssl-certfile", "../cert.pem"]
        restart: always
        ports:
            - 8008:8001

    mongo:
        image: mongo:latest
        env_file:
            - .env
            - .env.example
        ports:
            - 27018:27017
