services:
  lti_service:
    build:
      context: ./lti_auth
      dockerfile: Dockerfile
    env_file:
      - .env
    # extra_hosts:
    #   - "lms.local:host-gateway"
    # depends_on:
    #   - mongo
    ports:
      - "8001:80"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # depends_on:
    #   - lti_service
    command: npm run start:dev
    restart: always
    ports:
      - "8002:80"

  mongo:
    image: mongo:5.0
    env_file:
      - .env
    volumes:
      - mongodata:/data/db
    restart: always

volumes:
  mongodata:
