services:

  lti_service:
    build:
      context: ./lti_auth
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8001:80
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: npm run start:dev
    restart: always
    ports:
      - 8002:80

  mongo:
    image: mongo:5.0
    env_file:
      - .env
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
